name: "setup-cde-cli"
description: install and configure cloudera cde cli
inputs:
  version:
    required: true
    description: "Version of cde to install"
  access_key_id:
    required: true
    description: "access key id"
  private_key:
    required: true
    description: "private key"
  codeartifact_domain:
    required: true
    description: "CodeArtifact domain"
  codeartifact_repository:
    required: true
    description: "CodeArtifact repository name"
  vcluster_endpoint:
    required: true
    description: "vcluster-endpoint url"
runs:
  using: "composite"
  steps:
    - name: Set Up CDE CLI
      run: |
        aws codeartifact get-package-version-asset \
            --domain ${{ inputs.codeartifact_domain }} \
            --repository ${{ inputs.codeartifact_repository }} \
            --format generic \
            --namespace cli \
            --package cde \
            --package-version ${{ inputs.version }} \
            --asset cde cde \
            --no-cli-pager
        chmod +x ./cde
        sudo mv ./cde /usr/local/bin/cde
      shell: bash
    - name: Ensure Directories Exist with Correct Permissions
      run: |
        mkdir -p $HOME/.cdp
        mkdir -p $HOME/.cde
        chmod 700 $HOME/.cdp
        chmod 700 $HOME/.cde
      shell: bash
    - name: Write Credentials Config
      run: |
        echo "[default]" > $HOME/.cdp/credentials
        echo "cdp_access_key_id = ${{ inputs.access_key_id }}" >> $HOME/.cdp/credentials
        echo "cdp_private_key = ${{ inputs.private_key }}" >> $HOME/.cdp/credentials
      shell: bash
    - name: Write Profile Config
      run: |
        echo "vcluster-endpoint: ${{ inputs.vcluster_endpoint }}" > $HOME/.cde/config.yaml
      shell: bash