name: "undeploy-gh-runner"
description: Remove spawned GitHub Runners on Kubernetes through the Actions Runner Controller
branding:
  icon: package
  color: red
inputs:
  api_server:
    required: true
    description: "Kubernetes API Server address (must be public)"
  access_token:
    required: true
    description: "Kubernetes ServiceAccount access token"
  base64_encoded_ca_crt:
    required: true
    description: "CA certificate to connect to the API Server encoded in base64"
  runner_label:
    required: true
    description: "Runner label obtained during the runner deployment"
  namespace:
    required: false
    default: default
    description: "Namespace where the runner should be deployed"
runs:
  using: "docker"
  image: Dockerfile
  entrypoint: entrypoint.sh
  args:
    - ${{ inputs.api_server }}
    - ${{ inputs.access_token }}
    - ${{ inputs.base64_encoded_ca_crt }}
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
