apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ${RUNNER_LABEL}
  namespace: ${RUNNER_NAMESPACE}
spec:
  replicas: 1
  template:
    spec:
      repository: ${RUNNER_REPOSITORY}
      serviceAccountName: ${RUNNER_SERVICE_ACCOUNT}
      image: ${RUNNER_IMAGE}
      dockerdWithinRunnerContainer: ${RUNNER_DOCKER_ENABLED}
      labels:
        - ${RUNNER_LABEL}
