name: "undeploy-gh-runner"
description: Remove spawned GitHub Runners on Kubernetes through the Actions Runner Controller
branding:
  icon: package
  color: red
inputs:
  cluster_name:
    required: true
    description: "Name of the eks cluster to deploy on."
  aws_runner_deploy_role:
    required: true
    description: "Name of the aws role to use to deploy runners"
  aws_region:
    required: false
    default: "eu-central-1"
    description: "AWS region of the eks cluster"
  runner_label:
    required: true
    description: "Runner label obtained during the runner deployment"
  namespace:
    required: false
    default: default
    description: "Namespace where the runner should be deployed"
runs:
  using: "composite"
  steps:
    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_runner_deploy_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: setup kubectl
      run: |
        aws eks update-kubeconfig --name "${{ inputs.cluster_name }}" --region ${{ inputs.aws_region }}
      shell: bash  
    - name: Undeploy runner
      shell: bash
      run: |
        kubectl delete runnerdeployment ${{inputs.runner_label}} -n ${{inputs.namespace}} 
