name: "setup-cdp-cli"
description: install and configure cloudera cdp cli
inputs:
  version:
    required: true
    description: "Version of cdp to install"
  access_key_id:
    required: true
    description: "access key id"
  private_key:
    required: true
    description: "private key"
runs:
  using: "composite"
  steps:
    - name: Mask Sensitive Inputs
      run: |
        echo "::add-mask::${{ inputs.access_key_id }}"
        echo "::add-mask::${{ inputs.private_key }}"
      shell: bash

    - name: Install CDP CLI
      run: |
        pip install cdpcli==${{ inputs.version }}
      shell: bash

    - name: Configuration
      run: |
        mkdir -p "$HOME/.cdp"

        # Scrive il file credentials
        cat <<EOF > "$HOME/.cdp/credentials"
        [default]
        cdp_access_key_id = ${{ inputs.access_key_id }}
        cdp_private_key = ${{ inputs.private_key }}
        EOF

        chmod 600 "$HOME/.cdp/credentials"

        echo "CDP CLI configured successfully in $HOME/.cdp/credentials"
      shell: bash