name: Update Helm Chart and Deploy

on:
  workflow_call:
    inputs:
      eks-cluster:
        required: true
        type: string
      deploy-environment:
        required: true
        type: string

jobs:
  create-runner:
    name: Create Runner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Create Runner
        id: create_runner
        uses: pagopa/pdnd-github-actions/deploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          name: ${{ github.event.repository.name }}
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          namespace: ${{ vars.RUNNER_K8S_NAMESPACE }}
          image: ${{ vars.RUNNER_DOCKER_IMAGE }}
          service_account: ${{ vars.RUNNER_SERVICE_ACCOUNT }}
          docker_enabled: true
    outputs:
      runner_label: ${{ steps.create_runner.outputs.runner_label }}

  prepare-helm-update:
    name: Prepare Helm Chart Update
    needs: create-runner
    runs-on: [self-hosted, "${{ needs.create-runner.outputs.runner_label }}"]
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
      - name: Login to AWS ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
      - name: Get Current Chart Version
        id: current_version
        run: |
          echo "current_chart_version=$(yq e '.version' .k8s/helm/Chart.yaml)" >> "$GITHUB_OUTPUT"
      - name: Increment Chart Version
        id: increment_version
        run: |
          current_version=${{ steps.current_version.outputs.current_chart_version }}
          new_version=$(echo $current_version | awk -F. '{print $1"."$2"."$3+1}')
          echo "new_chart_version=$new_version" >> "$GITHUB_OUTPUT"
      - name: Update Chart Files
        run: |
          new_version=${{ steps.increment_version.outputs.new_chart_version }}
          yq e ".version = \"$new_version\"" -i .k8s/helm/Chart.yaml
          yq e ".appVersion = \"$new_version\"" -i .k8s/helm/Chart.yaml
      - name: Push Helm Chart to AWS ECR
        id: push_chart
        env:
          REGISTRY: ${{ steps.ecr_login.outputs.registry }}
          CHART_VERSION: ${{ steps.increment_version.outputs.new_chart_version }}
          APP_VERSION: ${{ steps.increment_version.outputs.new_chart_version }}
          CHART: ${{ github.event.repository.name }}
        run: |
          pwd
          ls -la
          cat .k8s/helm/Chart.yaml
          helm package .k8s/helm --version $CHART_VERSION --app-version $APP_VERSION
          ls -la
          cat .k8s/helm/Chart.yaml
          helm push $CHART-$CHART_VERSION.tgz oci://$REGISTRY/charts
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "Update Helm chart to version ${{ steps.increment_version.outputs.new_chart_version }}"
          file_pattern: '.k8s/helm/Chart.yaml .k8s/helm/values.yaml'

  deploy-to-k8s:
    name: Deploy to Kubernetes
    needs:
      - create-runner
      - prepare-helm-update
    runs-on: [self-hosted, "${{ needs.create-runner.outputs.runner_label }}"]
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
      - name: Get Target Namespace
        id: deploy_namespace
        run: |
          echo "deploy_namespace=$(yq e '.namespace' .k8s/helm/values.yaml)" >> "$GITHUB_OUTPUT"
      - name: Deploy to K8S via Helm
        id: helm_deploy
        env:
          HELM_RELEASE: ${{ github.event.repository.name }}
          HELM_REPOSITORY: .k8s/helm
          HELM_DEFAULT_VALUES: .k8s/helm/values.yaml
          HELM_NAMESPACE: ${{ steps.deploy_namespace.outputs.deploy_namespace }}
          HELM_ENV_VALUES: .k8s/helm/env-values/${{ inputs.deploy-environment }}.yaml
        run: |
          pwd
          ls -la
          cat .k8s/helm/Chart.yaml
          aws eks update-kubeconfig --region eu-central-1 --name ${{ inputs.eks-cluster }}
          helm upgrade --install $HELM_RELEASE $HELM_REPOSITORY -n $HELM_NAMESPACE -f $HELM_DEFAULT_VALUES -f $HELM_ENV_VALUES

  destroy-runner:
    name: Destroy Runner
    runs-on: ubuntu-latest
    needs:
      - create-runner
      - prepare-helm-update
      - deploy-to-k8s
    permissions:
      id-token: write
      contents: read
    if: ${{ always() }}
    steps:
      - name: Destroy Runner
        id: destroy_runner
        uses: pagopa/pdnd-github-actions/undeploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          runner_label: ${{ needs.create-runner.outputs.runner_label }}
          namespace:  ${{ vars.RUNNER_K8S_NAMESPACE }}
