name: Release Node UI - Dataviz
on:
  workflow_call:
    inputs:
      codebuild-runner:
        description: "Codebuild runner name"
        required: true
        type: string
      s3_url:
        required: false
        type: string
        description: 'S3 destination path in the format: s3://<bucket>/<project-name>/'
jobs:
    release:
      name: Release
      runs-on: ${{ inputs.codebuild-runner }}-${{ github.run_id }}-${{ github.run_attempt }}
      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
            id-token: write
            contents: read
      steps:
        - uses: nowsprinting/check-version-format-action@de7dcbd404b253dd775262e49c9924fa834e17a2 # v4.0.31
          id: version
          with:
            prefix: 'v'
        - name: Check version
          if: steps.version.outputs.is_valid == 'false'
          run: |
                echo "Version: ${{github.ref_name}} is not valid!"
                exit 1
        - name: Check out the repo
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        - name: Set S3 url from input
          if: inputs.s3_url != ''
          run: |
                echo "s3_url=${{ inputs.s3_url }}" >> "$GITHUB_ENV"
        - name: Set S3 url from repo name
          if: inputs.s3_url == ''
          run: |
                REPO=${{ github.event.repository.name }}
                S3_BUCKET="pdnd-prod-dl-1-dataviz"
                PROJECT=${REPO#*pdnd-dataviz-}
                if echo $REPO | grep -iq "pdnd-apps-ui"; then
                    S3_BUCKET="pdnd-prod-dl-1-apps"
                    PROJECT=${REPO#*pdnd-apps-ui-}
                fi
                echo "s3_url=s3://$S3_BUCKET/$PROJECT/" >> "$GITHUB_ENV"
        - name: Install dependencies & Build
          env:
            REACT_APP_AIRFLOW_CRED: ${{ secrets.AIRFLOW_USERNAME }}:${{ secrets.AIRFLOW_PASSWORD }}
          run: |
                npm ci
                npm run build
                if [ -d dist ]; then 
                  mv dist build 
                fi
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
          with:
            role-to-assume: arn:aws:iam::${{vars.AWS_IAM_ACCOUNT_ID}}:role/dataviz-sa-gh-assumable-role
            aws-region: eu-central-1
        - name: Deploy static site to S3 bucket
          run: aws s3 sync ./build ${{env.s3_url}} --delete --exclude "data/*"
        - name: Slack Notification
          uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25
          if: always()
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            status: ${{ job.status }}
            notification_title: "{workflow} has {status_message}"
            message_format: "{emoji} *{workflow}* <https://github.com/{repo}/actions/runs/${{ github.run_id }}|${{github.ref_name}}> {status_message} in <{repo_url}|{repo}>"
            footer: "<{repo_url}|Repo> | <{workflow_url}|Workflow>"
            notify_when: "success,failure,warnings"
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}