name: Release Please - Microservice
on:
  workflow_call:

jobs:
  create_runner:
    name: Create Runner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Create Runner
        id: create_runner
        uses: pagopa/pdnd-github-actions/deploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          name: ${{ github.event.repository.name }}
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          namespace: ${{ vars.RUNNER_K8S_NAMESPACE }}
          image: ${{ vars.RUNNER_DOCKER_IMAGE }}
          service_account: ${{ vars.RUNNER_SERVICE_ACCOUNT }}        
          docker_enabled: true
    outputs:
      runner_label: ${{ steps.create_runner.outputs.runner_label }}
  publish_artifacts:
    name: Publish Artifacts
    runs-on: [self-hosted, "${{ needs.create_runner.outputs.runner_label }}"]
    needs:
      - create_runner
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Create AWS ECR Docker Registry
        id: ecr_docker_registry
        uses: pagopa/pdnd-github-actions/create-ecr-repository@74cf3f8abfacd6814b924408a11b02f177f8f5a3
        with:
          repositoryName: ${{ github.event.repository.name }}
      - name: Create AWS ECR Helm Repository
        id: ecr_helm_repository
        uses: pagopa/pdnd-github-actions/create-ecr-repository@74cf3f8abfacd6814b924408a11b02f177f8f5a3
        with:
          repositoryName: charts/${{ github.event.repository.name }}
      - name: Login to AWS ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v2
      - name: Publish Container Image to AWS ECR
        id: image_publish
        env:
          REGISTRY: ${{ steps.ecr_login.outputs.registry }}
          REPOSITORY: ${{ github.event.repository.name }}
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG=$(jq -r '."."' .release-please-manifest.json)
          docker build \
              --build-arg DOCKER_REGISTRY_URI=$REGISTRY \
              -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
      - name: Update Helm Values
        id: update_values
        env:
          REPOSITORY: ${{ github.event.repository.name }}
        run: |
          IMAGE_TAG=$(jq -r '."."' .release-please-manifest.json)
          LATEST_SHA=$(aws ecr describe-images --repository-name $REPOSITORY --image-ids imageTag=$IMAGE_TAG | jq -r '.[] | .[].imageDigest') \
          yq e '.image.digest = env(LATEST_SHA)' -i .k8s/helm/$REPOSITORY/values.yaml
      - name: Push Helm Chart to AWS ECR
        env:
          REGISTRY: ${{ steps.ecr_login.outputs.registry }}
          CHART: ${{ github.event.repository.name }}
        run: |
          CHART_VERSION=$(jq -r '."."' .release-please-manifest.json)
          APP_VERSION=$(jq -r '."."' .release-please-manifest.json)
          helm package .k8s/helm --version $CHART_VERSION --app-version $APP_VERSION
          helm push $CHART-$CHART_VERSION.tgz oci://$REGISTRY/charts
      - name: Commit Helm Values
        id: commit_values
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit: update helm value image.digest to latest"
  destroy_runner:
    name: Destroy Runner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ always() && !contains(needs.create_runner.result, 'failure') && !contains(needs.create_runner.result, 'skipped')}}
    needs:
      - create_runner
      - publish_artifacts
    steps:
      - name: Destroy Runner
        id: destroy_runner
        uses: pagopa/pdnd-github-actions/undeploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          runner_label: ${{ needs.create_runner.outputs.runner_label }}
          namespace:  ${{ vars.RUNNER_K8S_NAMESPACE }}