name: Release Please - Prepare
on:
  workflow_call:

jobs:
  create_runner:
    name: Create Runner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Create Runner
        id: create_runner
        uses: pagopa/pdnd-github-actions/deploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          name: ${{ github.event.repository.name }}
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          namespace: ${{ vars.RUNNER_K8S_NAMESPACE }}
          image: ${{ vars.RUNNER_DOCKER_IMAGE }}
          service_account: ${{ vars.RUNNER_SERVICE_ACCOUNT }}        
          docker_enabled: true
    outputs:
      runner_label: ${{ steps.create_runner.outputs.runner_label }}
  prepare_release:
    name: Prepare Release
    runs-on: [self-hosted, "${{ needs.create_runner.outputs.runner_label }}"]
    needs:
      - create_runner
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Release-Please
        id: release_please
        uses: google-github-actions/release-please-action@v4
      - name: Get Release PR Number
        id: pr_number
        run: |
          echo "RELEASE_PR_NUMBER=$(jq -r '.number' <<< ${{ toJSON(steps.release_please.outputs.pr) }})" >> "$GITHUB_OUTPUT"
      - name: Approve Release PR
        id: approve_pr
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.pr_number.outputs.RELEASE_PR_NUMBER }}
          github-token: ${{ secrets.PAT_BOT }}
      - name: Merge Release PR
        id: merge_pr
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_BOT }}
          PULL_REQUEST: ${{ steps.pr_number.outputs.RELEASE_PR_NUMBER }}
          MERGE_LABELS: "autorelease: pending"
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          MERGE_COMMIT_MESSAGE: "Automerge PR #${{ steps.pr_number.outputs.RELEASE_PR_NUMBER }}"
  destroy_runner:
    name: Destroy Runner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ always() && !contains(needs.create_runner.result, 'failure') && !contains(needs.create_runner.result, 'skipped')}}
    needs:
      - create_runner
      - prepare_release
    steps:
      - name: Destroy Runner
        id: destroy_runner
        uses: pagopa/pdnd-github-actions/undeploy-eks-gh-runner@7fb09afd4227db40789da70cbdaa2c7157abff49
        with:
          cluster_name: ${{ vars.RUNNER_CLUSTER_NAME }}
          aws_runner_deploy_role: ${{ secrets.AWS_RUNNER_DEPLOY_ROLE }}
          runner_label: ${{ needs.create_runner.outputs.runner_label }}
          namespace:  ${{ vars.RUNNER_K8S_NAMESPACE }}