name: Release
on:
  workflow_call:
    inputs:
      codebuild-runner:
        description: "Codebuild runner name"
        required: true
        type: string
jobs:
  release:
      name: Release
      runs-on: ${{ inputs.codebuild-runner }}-${{ github.run_id }}-${{ github.run_attempt }}
      steps:
        - uses: nowsprinting/check-version-format-action@de7dcbd404b253dd775262e49c9924fa834e17a2 # v4.0.3
          id: version
          with:
            prefix: 'v'
        - name: Check version
          if: steps.version.outputs.is_valid == 'false'
          run: |
                echo "Version: ${{github.ref_name}} is not valid!"
                exit 1
        - name: Check out the repo
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        - name: Setup Python
          uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
          with:
            python-version: '3.12'
        - name: Login to code artifact
          run: |
            echo CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ vars.CODE_ARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
              --query authorizationToken --output text --region ${{ vars.AWS_REGION }}) >> $GITHUB_ENV
            echo "REPOSITORY_ENDPOINT=$(aws codeartifact get-repository-endpoint --domain ${{ vars.CODE_ARTIFACT_DOMAIN }}  \
              --domain-owner ${{ secrets.AWS_ACCOUNT_ID }}  --repository ${{ vars.CODE_ARTIFACT_INTERNAL_REPO }}  --format pypi --query repositoryEndpoint --output text)" >> $GITHUB_ENV
        - name: Build pkg
          run: |
                echo '__version__="'${{ steps.version.outputs.full }}'"' > _version.py
                python3 setup.py sdist bdist_wheel
        - name: Publish pkg
          uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
          with:
            user: aws
            password: ${{env.CODEARTIFACT_AUTH_TOKEN}}
            repository-url: ${{ env.REPOSITORY_ENDPOINT}}
        - name: Slack Notification
          uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25
          if: always() 
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            status: ${{ job.status }}
            notification_title: "{workflow} has {status_message}"
            message_format: "{emoji} *{workflow}* <https://github.com/{repo}/actions/runs/${{ github.run_id }}|${{github.ref_name}}> {status_message} in <{repo_url}|{repo}>"
            footer: "<{repo_url}|Repo> | <{workflow_url}|Workflow>"
            notify_when: "success,failure,warnings"
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
