name: Test Setup CDE CLI

on: push
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug
        run: |
          pwd
          ls -la
          cd ..
          pwd
          ls -la

      - name: Setup CDE CLI
        #uses: ../../setup-cde-cli/action.yml
        uses: pagopa/pdnd-github-actions/setup-cde-cli@PA-1167
        with:
        #  version: "1.0.0"
          access_key_id: ${{ secrets.ACCESS_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Verify CDE CLI installation
        run: |
          cde --version
